locations:
    master: '/home/gianthk/Data/BEATS/IH/scratch/master.csv'
    experiment: '~/Data/'
    recon: '/home/gianthk/Data/BEATS/IH/scratch/pippo/recon'
    cor: '/home/gianthk/Data/BEATS/IH/scratch/pippo/cor'
    imagej: '/opt/fiji-linux64/Fiji.app/ImageJ-linux64'
general:
    ncore: 4
load:
    normalize: True
    sino_range: [980, 1020]
    proj_range: [0, 4001]
normalize:
    averaging: 'mean'
cor:
    cor: 1280
    step: 1
    autoguess: False
    algorithm: 'TomoPy'
phase-retrieval:
    phase_object: False
    pixelsize: 6.5
    energy: 20.
    sdd: 20.
    alpha: 0.002
recon:
    algorithm: 'gridrec'
output:
    uintconvert: False
    bitdepth: 'uint8'
    circmask: False
    circ_mask_ratio: 0.9
plotting:
    plotreconhist: False
    speed: 'fast'